#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
REPORT_DIR="${STAGE_FINAL_REPORT_DIR:-$ROOT_DIR/.local/stage-final-reports}"
TS="$(date +%Y%m%d-%H%M%S)"
REPORT_JSON="$REPORT_DIR/stage-final-$TS.json"
REPORT_LOG="$REPORT_DIR/stage-final-$TS.log"

mkdir -p "$REPORT_DIR"
cd "$ROOT_DIR"

log() {
  printf '[check:stage-final] %s\n' "$*" | tee -a "$REPORT_LOG"
}

latest_file() {
  local pattern="$1"
  find "$ROOT_DIR" -path "$pattern" -type f -print0 2>/dev/null \
    | xargs -0 ls -t 2>/dev/null \
    | head -n 1
}

latest_file_in_dir() {
  local dir="$1"
  local pattern="$2"
  find "$dir" -maxdepth 1 -name "$pattern" -type f -print0 2>/dev/null \
    | xargs -0 ls -t 2>/dev/null \
    | head -n 1
}

latest_android_report_by_mode() {
  local mode="$1"
  local report_dir="${ANDROID_LIVE_REPORT_DIR:-$ROOT_DIR/.local/android-live-reports}"
  node - "$report_dir" "$mode" <<'NODE'
const fs = require("node:fs");
const path = require("node:path");
const dir = process.argv[2];
const mode = process.argv[3];
if (!dir || !fs.existsSync(dir)) {
  process.exit(0);
}
const records = [];
for (const name of fs.readdirSync(dir)) {
  if (!/^android-live-.*\.json$/.test(name)) continue;
  const file = path.join(dir, name);
  try {
    const report = JSON.parse(fs.readFileSync(file, "utf8"));
    const expectsNoAssistantQuery = report?.verdict?.expectsNoAssistantQuery === true;
    const expectsAutoVideo = report?.verdict?.expectsAutoVideo === true;
    if (
      (mode === "no-arm" && expectsNoAssistantQuery) ||
      (mode === "auto-video" && expectsAutoVideo) ||
      (mode === "primary" && !expectsNoAssistantQuery && !expectsAutoVideo)
    ) {
      records.push({ file, generatedAt: Number(report.generatedAt || 0) });
    }
  } catch {
    // Ignore partial/invalid reports.
  }
}
records.sort((a, b) => b.generatedAt - a.generatedAt || b.file.localeCompare(a.file));
if (records[0]) {
  process.stdout.write(records[0].file);
}
NODE
}

if [[ "${RUN_PHASE:-0}" == "1" ]]; then
  log "RUN_PHASE=1; running npm run check:phase first"
  npm run check:phase 2>&1 | tee -a "$REPORT_LOG"
fi

if [[ "${ALLOW_EMULATOR_FINAL:-0}" == "1" ]]; then
  log "ALLOW_EMULATOR_FINAL=1; physical-device check is relaxed for gate-shape debugging only"
  log "Emulator reports generated by check:android-live still have phaseReadyForRelease=false and cannot sign off release."
fi

PHASE_JSON="${PHASE_JSON:-$(latest_file "$ROOT_DIR/.local/current-phase-reports/current-phase-*.json")}"
ANDROID_LIVE_REPORT_DIR="${ANDROID_LIVE_REPORT_DIR:-$ROOT_DIR/.local/android-live-reports}"
ANDROID_LIVE_JSON="${ANDROID_LIVE_JSON:-$(latest_android_report_by_mode primary)}"
ANDROID_NO_ARM_JSON="${ANDROID_NO_ARM_JSON:-$(latest_android_report_by_mode no-arm)}"
ANDROID_AUTO_VIDEO_JSON="${ANDROID_AUTO_VIDEO_JSON:-$(latest_android_report_by_mode auto-video)}"
ANDROID_PREFLIGHT_JSON="${ANDROID_PREFLIGHT_JSON:-$(latest_file_in_dir "$ANDROID_LIVE_REPORT_DIR" "preflight-*.json")}"
ALLOW_EMULATOR_FINAL="${ALLOW_EMULATOR_FINAL:-0}"
REQUIRE_AUTO_VIDEO_LIVE="${REQUIRE_AUTO_VIDEO_LIVE:-0}"

log "phase_json=${PHASE_JSON:-<missing>}"
log "android_live_json=${ANDROID_LIVE_JSON:-<missing>}"
log "android_no_arm_json=${ANDROID_NO_ARM_JSON:-<missing>}"
log "android_auto_video_json=${ANDROID_AUTO_VIDEO_JSON:-<missing>}"
log "android_preflight_json=${ANDROID_PREFLIGHT_JSON:-<missing>}"

PHASE_JSON="$PHASE_JSON" \
ANDROID_LIVE_JSON="$ANDROID_LIVE_JSON" \
ANDROID_NO_ARM_JSON="$ANDROID_NO_ARM_JSON" \
ANDROID_AUTO_VIDEO_JSON="$ANDROID_AUTO_VIDEO_JSON" \
ANDROID_PREFLIGHT_JSON="$ANDROID_PREFLIGHT_JSON" \
ALLOW_EMULATOR_FINAL="$ALLOW_EMULATOR_FINAL" \
REQUIRE_AUTO_VIDEO_LIVE="$REQUIRE_AUTO_VIDEO_LIVE" \
REPORT_JSON="$REPORT_JSON" \
node <<'NODE'
const fs = require("node:fs");

function fail(message, details = {}) {
  const report = {
    ok: false,
    generatedAt: Date.now(),
    failure: message,
    ...details,
  };
  fs.writeFileSync(process.env.REPORT_JSON, `${JSON.stringify(report, null, 2)}\n`);
  console.error(JSON.stringify(report, null, 2));
  process.exit(1);
}

function readJson(path, label) {
  if (!path || !fs.existsSync(path)) {
    const details = { path: path || null };
    if (label === "android_live") {
      details.latestPreflightReport = process.env.ANDROID_PREFLIGHT_JSON || null;
      details.nextCommands = [
        "npm run check:android-live:doctor",
        "npm run check:android-live",
        "scripts/check-android-live.sh arm-query auto",
        "PRESERVE_LOGCAT=1 scripts/check-android-live.sh arm-query meeting",
        "PRESERVE_LOGCAT=1 scripts/check-android-live.sh stop-tts",
        "PRESERVE_LOGCAT=1 scripts/check-android-live.sh capture-video",
        "HUMAN_TTS_OK=1 HUMAN_ANSWER_RELEVANT=1 scripts/check-android-live.sh collect",
        "scripts/check-android-live.sh observe-ambient",
        "EXPECT_NO_ASSISTANT_QUERY=1 scripts/check-android-live.sh collect",
      ];
    } else if (label === "android_no_arm") {
      details.latestPreflightReport = process.env.ANDROID_PREFLIGHT_JSON || null;
      details.nextCommands = [
        "scripts/check-android-live.sh observe-ambient",
        "EXPECT_NO_ASSISTANT_QUERY=1 scripts/check-android-live.sh collect",
      ];
    }
    fail(`${label}_report_missing`, details);
  }
  try {
    return JSON.parse(fs.readFileSync(path, "utf8"));
  } catch (error) {
    fail(`${label}_report_invalid_json`, { path, error: String(error?.message || error) });
  }
}

function requireTrue(value, label, failures) {
  if (value !== true) {
    failures.push(label);
  }
}

function requireAtLeast(value, expected, label, failures) {
  if (!Number.isFinite(value) || value < expected) {
    failures.push(`${label}:expected>=${expected}:actual=${value}`);
  }
}

const phase = readJson(process.env.PHASE_JSON, "current_phase");
const live = readJson(process.env.ANDROID_LIVE_JSON, "android_live");
const noArm = readJson(process.env.ANDROID_NO_ARM_JSON, "android_no_arm");
const requireAutoVideoLive = process.env.REQUIRE_AUTO_VIDEO_LIVE === "1";
const autoVideo =
  process.env.ANDROID_AUTO_VIDEO_JSON && fs.existsSync(process.env.ANDROID_AUTO_VIDEO_JSON)
    ? readJson(process.env.ANDROID_AUTO_VIDEO_JSON, "android_auto_video")
    : null;
const failures = [];
const phaseGeneratedAt = Number(phase.generatedAt || 0);
const liveGeneratedAt = Number(live.generatedAt || 0);
const noArmGeneratedAt = Number(noArm.generatedAt || 0);
const autoVideoGeneratedAt = Number(autoVideo?.generatedAt || 0);

requireTrue(phase.ok, "current_phase.ok", failures);
if (!Number.isFinite(phaseGeneratedAt) || phaseGeneratedAt <= 0) {
  failures.push(`current_phase.generatedAt:${phase.generatedAt ?? "<missing>"}`);
}
if (phase.acceptance?.phaseState !== "ready-to-close") {
  failures.push(`current_phase.acceptance.phaseState:${phase.acceptance?.phaseState ?? "<missing>"}`);
}
if (phase.acceptance?.passedCriteria !== phase.acceptance?.totalCriteria) {
  failures.push(
    `current_phase.acceptance.criteria:${phase.acceptance?.passedCriteria ?? "<missing>"}/${phase.acceptance?.totalCriteria ?? "<missing>"}`,
  );
}
if (phase.videoAcceptance?.hostModelVideoMode !== "keyframes") {
  failures.push(`current_phase.video.mode:${phase.videoAcceptance?.hostModelVideoMode ?? "<missing>"}`);
}
requireAtLeast(phase.videoAcceptance?.playableVideoArtifacts, 1, "current_phase.video.playableVideoArtifacts", failures);
requireAtLeast(phase.videoAcceptance?.videoRequestGroups, 1, "current_phase.video.videoRequestGroups", failures);
requireAtLeast(phase.videoEvidence?.transcriptSpans, 1, "current_phase.video.transcriptSpans", failures);
requireAtLeast(phase.videoEvidence?.keyframeDetails, 1, "current_phase.video.keyframeDetails", failures);

requireTrue(live.ok, "android_live.ok", failures);
if (!Number.isFinite(liveGeneratedAt) || liveGeneratedAt <= 0) {
  failures.push(`android_live.generatedAt:${live.generatedAt ?? "<missing>"}`);
} else if (Number.isFinite(phaseGeneratedAt) && phaseGeneratedAt > 0 && liveGeneratedAt < phaseGeneratedAt) {
  failures.push(`android_live.stale:liveGeneratedAt=${liveGeneratedAt}:phaseGeneratedAt=${phaseGeneratedAt}`);
}
if (process.env.ALLOW_EMULATOR_FINAL !== "1") {
  requireTrue(live.verdict?.physicalAndroidDevice, "android_live.physicalAndroidDevice", failures);
}
requireTrue(live.verdict?.hostDeviceSeen, "android_live.hostDeviceSeen", failures);
requireTrue(live.verdict?.voiceLoopObserved, "android_live.voiceLoopObserved", failures);
if (live.verdict?.ttsStatus !== "pass") {
  failures.push(`android_live.ttsStatus:${live.verdict?.ttsStatus ?? "<missing>"}`);
}
requireTrue(live.verdict?.humanTtsOk, "android_live.humanTtsOk", failures);
requireTrue(live.verdict?.humanAnswerRelevant, "android_live.humanAnswerRelevant", failures);
requireTrue(live.verdict?.stopTtsObserved, "android_live.stopTtsObserved", failures);
if (live.verdict?.videoStatus !== "upload-observed") {
  failures.push(`android_live.videoStatus:${live.verdict?.videoStatus ?? "<missing>"}`);
}
requireTrue(live.verdict?.authStable, "android_live.authStable", failures);
requireTrue(live.verdict?.phaseReadyForRelease, "android_live.phaseReadyForRelease", failures);
requireAtLeast(live.host?.videoEvidenceGroups, 1, "android_live.host.videoEvidenceGroups", failures);
requireAtLeast(live.host?.videoTranscriptSpans, 1, "android_live.host.videoTranscriptSpans", failures);
requireAtLeast(live.host?.videoKeyframeDetails, 1, "android_live.host.videoKeyframeDetails", failures);

requireTrue(noArm.ok, "android_no_arm.ok", failures);
if (!Number.isFinite(noArmGeneratedAt) || noArmGeneratedAt <= 0) {
  failures.push(`android_no_arm.generatedAt:${noArm.generatedAt ?? "<missing>"}`);
} else if (Number.isFinite(phaseGeneratedAt) && phaseGeneratedAt > 0 && noArmGeneratedAt < phaseGeneratedAt) {
  failures.push(`android_no_arm.stale:noArmGeneratedAt=${noArmGeneratedAt}:phaseGeneratedAt=${phaseGeneratedAt}`);
}
requireTrue(noArm.verdict?.expectsNoAssistantQuery, "android_no_arm.expectsNoAssistantQuery", failures);
requireTrue(noArm.verdict?.noArmAmbientQueryClean, "android_no_arm.noArmAmbientQueryClean", failures);
if (noArm.verdict?.noArmAmbientQueryPollution !== false) {
  failures.push(`android_no_arm.noArmAmbientQueryPollution:${noArm.verdict?.noArmAmbientQueryPollution ?? "<missing>"}`);
}
if (Number(noArm.logs?.assistantQueryArmed || 0) > 0) {
  failures.push(`android_no_arm.logs.assistantQueryArmed:${noArm.logs.assistantQueryArmed}`);
}
if (Number(noArm.logs?.assistantQueryCaptured || 0) > 0) {
  failures.push(`android_no_arm.logs.assistantQueryCaptured:${noArm.logs.assistantQueryCaptured}`);
}
if (Number(noArm.logs?.assistantQuerySubmitting || 0) > 0) {
  failures.push(`android_no_arm.logs.assistantQuerySubmitting:${noArm.logs.assistantQuerySubmitting}`);
}
if (Number(noArm.logs?.assistantQueryAnswered || 0) > 0) {
  failures.push(`android_no_arm.logs.assistantQueryAnswered:${noArm.logs.assistantQueryAnswered}`);
}

if (requireAutoVideoLive) {
  if (!autoVideo) {
    failures.push("android_auto_video_report_missing");
  } else {
    requireTrue(autoVideo.ok, "android_auto_video.ok", failures);
    if (!Number.isFinite(autoVideoGeneratedAt) || autoVideoGeneratedAt <= 0) {
      failures.push(`android_auto_video.generatedAt:${autoVideo?.generatedAt ?? "<missing>"}`);
    } else if (Number.isFinite(phaseGeneratedAt) && phaseGeneratedAt > 0 && autoVideoGeneratedAt < phaseGeneratedAt) {
      failures.push(
        `android_auto_video.stale:autoVideoGeneratedAt=${autoVideoGeneratedAt}:phaseGeneratedAt=${phaseGeneratedAt}`,
      );
    }
    if (process.env.ALLOW_EMULATOR_FINAL !== "1") {
      requireTrue(autoVideo.verdict?.physicalAndroidDevice, "android_auto_video.physicalAndroidDevice", failures);
    }
    requireTrue(autoVideo.verdict?.expectsAutoVideo, "android_auto_video.expectsAutoVideo", failures);
    requireTrue(autoVideo.verdict?.autoVideoObserved, "android_auto_video.autoVideoObserved", failures);
    requireTrue(autoVideo.verdict?.autoVideoLiveReady, "android_auto_video.autoVideoLiveReady", failures);
    requireTrue(autoVideo.verdict?.authStable, "android_auto_video.authStable", failures);
    if (autoVideo.verdict?.videoStatus !== "upload-observed") {
      failures.push(`android_auto_video.videoStatus:${autoVideo.verdict?.videoStatus ?? "<missing>"}`);
    }
    requireAtLeast(autoVideo.logs?.autoVideoUploadSucceeded, 1, "android_auto_video.logs.autoVideoUploadSucceeded", failures);
    requireAtLeast(autoVideo.host?.videoEvidenceGroups, 1, "android_auto_video.host.videoEvidenceGroups", failures);
    requireAtLeast(autoVideo.host?.videoKeyframeDetails, 1, "android_auto_video.host.videoKeyframeDetails", failures);
  }
}

const report = {
  ok: failures.length === 0,
  generatedAt: Date.now(),
  phaseReport: process.env.PHASE_JSON,
  androidLiveReport: process.env.ANDROID_LIVE_JSON,
  androidNoArmReport: process.env.ANDROID_NO_ARM_JSON,
  androidAutoVideoReport: process.env.ANDROID_AUTO_VIDEO_JSON || null,
  failures,
  summary: {
    phase: phase.acceptance,
    phaseGeneratedAt,
    videoAcceptance: phase.videoAcceptance,
    androidLive: live.verdict,
    androidLiveGeneratedAt: liveGeneratedAt,
    androidNoArm: noArm.verdict,
    androidNoArmGeneratedAt: noArmGeneratedAt,
    androidAutoVideo: autoVideo?.verdict || null,
    androidAutoVideoGeneratedAt: autoVideoGeneratedAt || null,
    requireAutoVideoLive,
    androidDevice: live.androidDevice,
    androidPackage: live.androidPackage,
    allowEmulatorFinal: process.env.ALLOW_EMULATOR_FINAL === "1",
    androidLogs: live.logs,
    androidHost: live.host,
  },
};

fs.writeFileSync(process.env.REPORT_JSON, `${JSON.stringify(report, null, 2)}\n`);
console.log(JSON.stringify(report, null, 2));

if (failures.length > 0) {
  process.exit(1);
}
NODE

log "ok"
